apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: ipam-ctlr
  name: ipam-ctlr
  namespace: cis-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipam-ctlr
  template:
    metadata:
      labels:
        app: ipam-ctlr
    spec:
      containers:
      - args:
        - --orchestration=kubernetes
        - --ip-range='{"Test":"172.16.3.31-172.16.3.40"}'
        - --log-level=DEBUG
        command:
        - /app/bin/f5-ipam-controller
        image: f5networks/f5-ipam-controller:latest
        imagePullPolicy: IfNotPresent
        name: ipam-ctlr
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /app/ipamdb
          name: samplevol
      securityContext:
        fsGroup: 1200
        runAsGroup: 1200
        runAsUser: 1200
      volumes:
      - name: samplevol
        emptyDir:
          sizeLimit: 1Gi
#       persistentVolumeClaim:
#         claimName: pvc-local
      serviceAccount: ipam-ctlr
      serviceAccountName: ipam-ctlr
