apiVersion: v1
kind: Service
metadata:
  annotations:
    cis.f5.com/ipamLabel: Test
    cis.f5.com/health: '{"interval": 10, "timeout": 31}'
  name: lb-f5-hello-world-web
  namespace: default
  labels:
    app: f5-hello-world-web
spec:
  ports:
  - name: f5-hello-world-web
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: f5-hello-world-web
